### ISSUE TITLE
CFML2 instructions should link here

### ISSUE THREAD

**Issue by talex5** [charguer/tlc#5]
I'm trying to install CFML2 (after reading the draft of "Volume 6: Separation Logic Foundations", which was very interesting - thanks for writing this!), to try verifying some actual OCaml code.

The instructions at https://gitlab.inria.fr/charguer/cfml2 say to run `opam install coq-tlc.20181116`, but that package doesn't seem to exist. It then says to use `git clone https://gitlab.inria.fr/charguer/tlc -b coq-8.9`, but that requires a password. I found this repository by searching and assume this is the correct location. I don't have permission to report issues at inria.fr, so am reporting here instead.

Also:

- http://www.chargueraud.org/softs/cfml/ says to use CFML2 after 2020, but the `README` link in the CFML2 section links to CFML1.
- CFML1 seems to warn against using that version.
- I couldn't find any instructions on how to use CFML2 (i.e. how to take an existing `.ml` file and import it into Coq). The CFML2 repository doesn't seem to include any example `*.ml` files.

**Comment by charguer** [comment]
Thanks for your feedback.

Due to the amount of time that I invested in writing the course I have been slowed down on making CFML2 match all the features that were in CFML1.

In the course, you can verify pieces of code in near-OCaml syntax, following the example near the last lines of the file
http://www.chargueraud.org/teach/verif/slf/LibSepReference.html
(which shows how to avoid the quotes on variable names).

If you want to verify real OCaml code, at the moment only CFML1 works.
TLC is now on github, the old 8.9 branch is still there: https://github.com/charguer/tlc/tree/coq-8.9

CFML2 is not ready for external users at the moment, I still need to put in the OCaml front end. There are a few weeks of work, and I'm still working on polishing the course for the official release at the moment. Feel free to contact me by email (available on my webpage) if you have specific programs that you wish to verify.
